# Generated by Django 4.2.11 on 2024-04-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='seasons',
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tvlog.show'),
            preserve_default=False,
        ),
    ]
