# Generated by Django 4.2.11 on 2024-04-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvlog', '0002_remove_show_seasons_season_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlywatching',
            name='show',
        ),
    ]
