# Generated by Django 4.2.11 on 2024-04-02 19:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvlog', '0004_show_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlywatching',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='currentlywatching',
            name='rewatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='startdate',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentlywatching',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Watched',
        ),
    ]
