# Generated by Django 4.2.11 on 2024-04-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvlog', '0005_currentlywatching_rating_currentlywatching_rewatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='abbreviation',
            field=models.SlugField(),
        ),
    ]
