# Generated by Django 4.2.11 on 2024-04-13 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvlog', '0006_alter_show_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlywatching',
            name='episode',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='UserEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isEditor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
