# Generated by Django 4.2.11 on 2024-05-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvlog', '0008_userex_watchlist_alter_show_boxart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userex',
            name='displayname',
            field=models.CharField(default='Migrated User', max_length=75),
            preserve_default=False,
        ),
    ]
