# Generated by Django 4.2.11 on 2024-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvlog', '0009_userex_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userex',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
